### ISSUE TITLE
Add social links to theme footer

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/mkdocs-asf-theme#4]
https://asf.alaska.edu footer includes links to ASF twitter, facebook, and youtube.

Could be added to the theme via something like this in https://github.com/ASFHyP3/asf-mkdocs-theme/blob/develop/asf_theme/mkdocs_theme.yml

```
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Ak_Satellite
```
